/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk

/** 
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GawkStandaloneSetup extends GawkStandaloneSetupGenerated {
	def static void doSetup() {
		new GawkStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
