/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import uk.ac.kcl.mde.gawk.ui.AbstractGawkUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class GawkUiModule extends AbstractGawkUiModule {
  public GawkUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
