/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class GawkLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public GawkLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
