/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class GawkQuickfixProvider extends DefaultQuickfixProvider {
}
