/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.awk.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the Eclipse IDE.
 */
class AwkUiModule extends AbstractAwkUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
