/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.validation

import org.eclipse.xtext.validation.Check
import uk.ac.kcl.mde.gawk.gawk.GawkPackage
import uk.ac.kcl.mde.gawk.gawk.GawkProgram
import uk.ac.kcl.mde.gawk.gawk.SectionHeader

/** 
 * This class contains custom validation rules. 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GawkValidator extends AbstractGawkValidator { 

	public static val INVALID_SECTION = 'invalid_section'
	
	 @Check
	 def checkSectionHeaderNotDuplicate(GawkProgram program) {
		if (program.sections.filter[sectionBlock | sectionBlock.section == SectionHeader.START].size > 1) {
			warning('There should not be two start headers', program,
				GawkPackage.Literals.GAWK_PROGRAM__SECTIONS, INVALID_SECTION)
				
		}
	}
	
}
