/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ide;

import uk.ac.kcl.mde.gawk.ide.AbstractGawkIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GawkIdeModule extends AbstractGawkIdeModule {
}
