/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.mde.gawk.GawkRuntimeModule;
import uk.ac.kcl.mde.gawk.GawkStandaloneSetup;
import uk.ac.kcl.mde.gawk.ide.GawkIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GawkIdeSetup extends GawkStandaloneSetup {
  @Override
  public Injector createInjector() {
    GawkRuntimeModule _gawkRuntimeModule = new GawkRuntimeModule();
    GawkIdeModule _gawkIdeModule = new GawkIdeModule();
    return Guice.createInjector(Modules2.mixin(_gawkRuntimeModule, _gawkIdeModule));
  }
}
