/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.gawk.ui.contentassist;

import uk.ac.kcl.mde.gawk.ui.contentassist.AbstractGawkProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GawkProposalProvider extends AbstractGawkProposalProvider {
}
