/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.awk

/** 
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AwkRuntimeModule extends AbstractAwkRuntimeModule {
}
