/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.mde.awk

/** 
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AwkStandaloneSetup extends AwkStandaloneSetupGenerated {
	def static void doSetup() {
		new AwkStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
